#ifndef Scadaddle_dbKeys_h
#define Scadaddle_dbKeys_h

#define kId @"id"
#define kUserID @"user_id"
#define kLocationId @"location_id"
#define kInterestId @"interest_id"
#define kTitle @"title"
#define kDescription @"description"
#define kReward @"reward"
#define kPlaces @"places"
#define kFacebook @"facebook"
#define kTwitter @"twitter"
#define kYoutube @"youtube"
#define kPromoted @"promoted"
#define kStatus @"status"
#define kCreated @"created"
#define kFacebookId @"fbid"
#define kEmail @"email"
#define kRole @"role"
#define kName @"name"
#define kAbout @"about"
#define kModeId @"mode_id"
#define kAccess @"access"
#define kLogin @"login"
#define kLanStatus @"lan_status"
#define kTimezone @"timezone"
#define kImage @"image"
#define kActivityTimes @"activity_times"
#define kActivityFiles @"activity_files"
#define kActivityFriends @"activity_friends"
#define kActivityInterests @"activity_interests"
#define kBusiness @"user_business"
#define kUserFiles @"user_files"
#define kPoints @"points"
#define kSettings @"settings"
#define kFriends @"friends"
#define kUserInterests @"user_interests"
#define kReferences @"user_references"
#define kActifities @"activities"
#define kSocialsDBFieldType @"type"
#define kSocialsDBFieldData @"data"
#define kNotificationDBField @"notification" 
#define kUserBirthday @"birthday" 
#define kFacebookAccessToken @"accessToken"
#endif
